// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kogleron/go-template/internal/apps"
	"github.com/kogleron/go-template/internal/bootstrap"
)

// Injectors from wire.go:

func initGoTemplate() (*apps.GoTemplate, error) {
	goTemplateConf := bootstrap.NewGoTemplateConf()
	goTemplate := apps.NewGoTemplate(goTemplateConf)
	return goTemplate, nil
}
